group: travis_latest
language: php
sudo: false

env:
  - TEST_SUITE=unit
  - TEST_SUITE=functional
  - TEST_SUITE=efficiency
php:
  - 7.2
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

install:
  - phpenv config-rm xdebug.ini || true;
  - composer update;

script:
  - |
    if [ "${TEST_SUITE}" = "unit" ]; then
      php vendor/bin/phpunit --exclude-group efficiency;
    elif [ "${TEST_SUITE}" = "efficiency" ]; then
      php vendor/bin/phpunit --group efficiency;
    elif [ "${TEST_SUITE}" = "functional" ]; then
      php vendor/bin/behat --strict;
    fi;